// Code generated by go run gob_gen.go; DO NOT EDIT.

package build_flags

import (
	"android/soong/android"
	"bytes"
	"fmt"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
	"reflect"
)

// begin of declarations.go
func init() {
	BuildFlagDeclarationsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(BuildFlagDeclarationsProviderData) })
}

func (r BuildFlagDeclarationsProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.IntermediateCacheOutputPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.IntermediateDumpOutputPath); err != nil {
		return err
	}
	return err
}

func (r BuildFlagDeclarationsProviderData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":build_flags.BuildFlagDeclarationsProviderData")
	hasher.WriteInt(2)
	hasher.WriteString(":build_flags.android.WritablePath")
	val1 := r.IntermediateCacheOutputPath == nil
	if val1 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.IntermediateCacheOutputPath); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val2 := r.IntermediateCacheOutputPath == nil
				if val2 {
					hasher.WriteByte(0)
				} else {
					val3 := func(hasher *proptools.Hasher) error {
						return r.IntermediateCacheOutputPath.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val3); err != nil {
						return err
					}
				}
			}
		} else {
			r.IntermediateCacheOutputPath.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.WritablePath")
	val4 := r.IntermediateDumpOutputPath == nil
	if val4 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.IntermediateDumpOutputPath); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val5 := r.IntermediateDumpOutputPath == nil
				if val5 {
					hasher.WriteByte(0)
				} else {
					val6 := func(hasher *proptools.Hasher) error {
						return r.IntermediateDumpOutputPath.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val6); err != nil {
						return err
					}
				}
			}
		} else {
			r.IntermediateDumpOutputPath.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	return nil
}

func (r *BuildFlagDeclarationsProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.IntermediateCacheOutputPath = nil
	} else {
		r.IntermediateCacheOutputPath = val2.(android.WritablePath)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.IntermediateDumpOutputPath = nil
	} else {
		r.IntermediateDumpOutputPath = val4.(android.WritablePath)
	}

	return err
}

var BuildFlagDeclarationsProviderDataGobRegId int16

func (r BuildFlagDeclarationsProviderData) GetTypeId() int16 {
	return BuildFlagDeclarationsProviderDataGobRegId
}

// end of declarations.go

// begin of release_configs.go
func init() {
	ReleaseConfigContributionsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ReleaseConfigContributionsProviderData) })
	ReleaseConfigProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ReleaseConfigProviderData) })
	AllReleaseConfigsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AllReleaseConfigsProviderData) })
}

func (r ReleaseConfigContributionsProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = r.ContributionDir.Encode(ctx, buf); err != nil {
		return err
	}

	if r.ContributionPaths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.ContributionPaths)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.ContributionPaths); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.ContributionPaths[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r ReleaseConfigContributionsProviderData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":build_flags.ReleaseConfigContributionsProviderData")
	hasher.WriteInt(2)
	if err := r.ContributionDir.CustomHash(hasher); err != nil {
		return err
	}
	hasher.WriteString(":build_flags.android.Paths")
	hasher.WriteString(":.[]Path")
	hasher.WriteInt(len(r.ContributionPaths))
	for val1 := 0; val1 < len(r.ContributionPaths); val1++ {
		hasher.WriteString("android/soong/android:android.Path")
		val2 := r.ContributionPaths[val1] == nil
		if val2 {
			hasher.WriteByte(0)
		} else {
			if v := reflect.ValueOf(r.ContributionPaths[val1]); v.Kind() == reflect.Ptr {
				if v.IsNil() {
					panic(fmt.Errorf("nil pointer is not supported in interface"))
				} else {
					val3 := r.ContributionPaths[val1] == nil
					if val3 {
						hasher.WriteByte(0)
					} else {
						val4 := func(hasher *proptools.Hasher) error {
							return r.ContributionPaths[val1].(proptools.CustomHash).CustomHash(hasher)
						}
						if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val4); err != nil {
							return err
						}
					}
				}
			} else {
				r.ContributionPaths[val1].(proptools.CustomHash).CustomHash(hasher)
			}
		}
	}
	return nil
}

func (r *ReleaseConfigContributionsProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if err = r.ContributionDir.Decode(ctx, buf); err != nil {
		return err
	}

	var val4 int
	err = gobtools.DecodeInt(buf, &val4)
	if err != nil {
		return err
	}
	if val4 != -1 {
		r.ContributionPaths = make([]android.Path, val4)
		for val5 := 0; val5 < int(val4); val5++ {
			if val7, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val7 == nil {
				r.ContributionPaths[val5] = nil
			} else {
				r.ContributionPaths[val5] = val7.(android.Path)
			}
		}
	}

	return err
}

var ReleaseConfigContributionsProviderDataGobRegId int16

func (r ReleaseConfigContributionsProviderData) GetTypeId() int16 {
	return ReleaseConfigContributionsProviderDataGobRegId
}

func (r ReleaseConfigProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsProductJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsSystemJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsSystemExtJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.BuildFlagsVendorJson); err != nil {
		return err
	}
	return err
}

func (r ReleaseConfigProviderData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":build_flags.ReleaseConfigProviderData")
	hasher.WriteInt(4)
	hasher.WriteString(":build_flags.android.Path")
	val1 := r.BuildFlagsProductJson == nil
	if val1 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.BuildFlagsProductJson); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val2 := r.BuildFlagsProductJson == nil
				if val2 {
					hasher.WriteByte(0)
				} else {
					val3 := func(hasher *proptools.Hasher) error {
						return r.BuildFlagsProductJson.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val3); err != nil {
						return err
					}
				}
			}
		} else {
			r.BuildFlagsProductJson.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.Path")
	val4 := r.BuildFlagsSystemJson == nil
	if val4 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.BuildFlagsSystemJson); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val5 := r.BuildFlagsSystemJson == nil
				if val5 {
					hasher.WriteByte(0)
				} else {
					val6 := func(hasher *proptools.Hasher) error {
						return r.BuildFlagsSystemJson.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val6); err != nil {
						return err
					}
				}
			}
		} else {
			r.BuildFlagsSystemJson.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.Path")
	val7 := r.BuildFlagsSystemExtJson == nil
	if val7 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.BuildFlagsSystemExtJson); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val8 := r.BuildFlagsSystemExtJson == nil
				if val8 {
					hasher.WriteByte(0)
				} else {
					val9 := func(hasher *proptools.Hasher) error {
						return r.BuildFlagsSystemExtJson.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val9); err != nil {
						return err
					}
				}
			}
		} else {
			r.BuildFlagsSystemExtJson.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.Path")
	val10 := r.BuildFlagsVendorJson == nil
	if val10 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.BuildFlagsVendorJson); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val11 := r.BuildFlagsVendorJson == nil
				if val11 {
					hasher.WriteByte(0)
				} else {
					val12 := func(hasher *proptools.Hasher) error {
						return r.BuildFlagsVendorJson.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val12); err != nil {
						return err
					}
				}
			}
		} else {
			r.BuildFlagsVendorJson.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	return nil
}

func (r *ReleaseConfigProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.BuildFlagsProductJson = nil
	} else {
		r.BuildFlagsProductJson = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.BuildFlagsSystemJson = nil
	} else {
		r.BuildFlagsSystemJson = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.BuildFlagsSystemExtJson = nil
	} else {
		r.BuildFlagsSystemExtJson = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.BuildFlagsVendorJson = nil
	} else {
		r.BuildFlagsVendorJson = val8.(android.Path)
	}

	return err
}

var ReleaseConfigProviderDataGobRegId int16

func (r ReleaseConfigProviderData) GetTypeId() int16 {
	return ReleaseConfigProviderDataGobRegId
}

func (r AllReleaseConfigsProviderData) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.AllReleaseConfigsDb); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AllReleaseConfigsTextproto); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.AllReleaseConfigsJson); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(ctx, buf, r.InheritanceGraphDot); err != nil {
		return err
	}
	return err
}

func (r AllReleaseConfigsProviderData) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":build_flags.AllReleaseConfigsProviderData")
	hasher.WriteInt(4)
	hasher.WriteString(":build_flags.android.Path")
	val1 := r.AllReleaseConfigsDb == nil
	if val1 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.AllReleaseConfigsDb); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val2 := r.AllReleaseConfigsDb == nil
				if val2 {
					hasher.WriteByte(0)
				} else {
					val3 := func(hasher *proptools.Hasher) error {
						return r.AllReleaseConfigsDb.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val3); err != nil {
						return err
					}
				}
			}
		} else {
			r.AllReleaseConfigsDb.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.Path")
	val4 := r.AllReleaseConfigsTextproto == nil
	if val4 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.AllReleaseConfigsTextproto); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val5 := r.AllReleaseConfigsTextproto == nil
				if val5 {
					hasher.WriteByte(0)
				} else {
					val6 := func(hasher *proptools.Hasher) error {
						return r.AllReleaseConfigsTextproto.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val6); err != nil {
						return err
					}
				}
			}
		} else {
			r.AllReleaseConfigsTextproto.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.Path")
	val7 := r.AllReleaseConfigsJson == nil
	if val7 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.AllReleaseConfigsJson); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val8 := r.AllReleaseConfigsJson == nil
				if val8 {
					hasher.WriteByte(0)
				} else {
					val9 := func(hasher *proptools.Hasher) error {
						return r.AllReleaseConfigsJson.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val9); err != nil {
						return err
					}
				}
			}
		} else {
			r.AllReleaseConfigsJson.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	hasher.WriteString(":build_flags.android.Path")
	val10 := r.InheritanceGraphDot == nil
	if val10 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.InheritanceGraphDot); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val11 := r.InheritanceGraphDot == nil
				if val11 {
					hasher.WriteByte(0)
				} else {
					val12 := func(hasher *proptools.Hasher) error {
						return r.InheritanceGraphDot.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val12); err != nil {
						return err
					}
				}
			}
		} else {
			r.InheritanceGraphDot.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	return nil
}

func (r *AllReleaseConfigsProviderData) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.AllReleaseConfigsDb = nil
	} else {
		r.AllReleaseConfigsDb = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val4 == nil {
		r.AllReleaseConfigsTextproto = nil
	} else {
		r.AllReleaseConfigsTextproto = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val6 == nil {
		r.AllReleaseConfigsJson = nil
	} else {
		r.AllReleaseConfigsJson = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val8 == nil {
		r.InheritanceGraphDot = nil
	} else {
		r.InheritanceGraphDot = val8.(android.Path)
	}

	return err
}

var AllReleaseConfigsProviderDataGobRegId int16

func (r AllReleaseConfigsProviderData) GetTypeId() int16 {
	return AllReleaseConfigsProviderDataGobRegId
}

// end of release_configs.go
