// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	AconfigDeclarationsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AconfigDeclarationsProviderData) })
	AconfigReleaseDeclarationsProviderDataGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(AconfigReleaseDeclarationsProviderData) })
	ModeInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModeInfo) })
	aconfigPropagatingDeclarationsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(aconfigPropagatingDeclarationsInfo) })
}

func (r AconfigDeclarationsProviderData) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Package); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Container); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.Exportable); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.IntermediateCacheOutputPath); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.IntermediateDumpOutputPath); err != nil {
		return err
	}
	return err
}

func (r *AconfigDeclarationsProviderData) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Package)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Container)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.Exportable)
	if err != nil {
		return err
	}

	if val5, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val5 == nil {
		r.IntermediateCacheOutputPath = nil
	} else {
		r.IntermediateCacheOutputPath = val5.(WritablePath)
	}

	if val7, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val7 == nil {
		r.IntermediateDumpOutputPath = nil
	} else {
		r.IntermediateDumpOutputPath = val7.(WritablePath)
	}

	return err
}

var AconfigDeclarationsProviderDataGobRegId int16

func (r AconfigDeclarationsProviderData) GetTypeId() int16 {
	return AconfigDeclarationsProviderDataGobRegId
}

func (r AconfigReleaseDeclarationsProviderData) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.Data))); err != nil {
		return err
	}
	for k, v := range r.Data {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = v.Encode(buf); err != nil {
			return err
		}
	}
	return err
}

func (r *AconfigReleaseDeclarationsProviderData) Decode(buf *bytes.Reader) error {
	var err error

	var val1 int32
	err = gobtools.DecodeSimple[int32](buf, &val1)
	if err != nil {
		return err
	}
	if val1 > 0 {
		r.Data = make(map[string]AconfigDeclarationsProviderData, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v AconfigDeclarationsProviderData
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			if err = v.Decode(buf); err != nil {
				return err
			}
			r.Data[k] = v
		}
	}

	return err
}

var AconfigReleaseDeclarationsProviderDataGobRegId int16

func (r AconfigReleaseDeclarationsProviderData) GetTypeId() int16 {
	return AconfigReleaseDeclarationsProviderDataGobRegId
}

func (r ModeInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.Container); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Mode); err != nil {
		return err
	}
	return err
}

func (r *ModeInfo) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.Container)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Mode)
	if err != nil {
		return err
	}

	return err
}

var ModeInfoGobRegId int16

func (r ModeInfo) GetTypeId() int16 {
	return ModeInfoGobRegId
}

func (r aconfigPropagatingDeclarationsInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.AconfigFiles))); err != nil {
		return err
	}
	for k, v := range r.AconfigFiles {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = gobtools.EncodeSimple(buf, int32(len(v))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(v); val1++ {
			if err = gobtools.EncodeInterface(buf, v[val1]); err != nil {
				return err
			}
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.ModeInfos))); err != nil {
		return err
	}
	for k, v := range r.ModeInfos {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = v.Encode(buf); err != nil {
			return err
		}
	}
	return err
}

func (r *aconfigPropagatingDeclarationsInfo) Decode(buf *bytes.Reader) error {
	var err error

	var val1 int32
	err = gobtools.DecodeSimple[int32](buf, &val1)
	if err != nil {
		return err
	}
	if val1 > 0 {
		r.AconfigFiles = make(map[string]Paths, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v Paths
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val6 int32
			err = gobtools.DecodeSimple[int32](buf, &val6)
			if err != nil {
				return err
			}
			if val6 > 0 {
				v = make([]Path, val6)
				for val7 := 0; val7 < int(val6); val7++ {
					if val9, err := gobtools.DecodeInterface(buf); err != nil {
						return err
					} else if val9 == nil {
						v[val7] = nil
					} else {
						v[val7] = val9.(Path)
					}
				}
			}
			r.AconfigFiles[k] = v
		}
	}

	var val10 int32
	err = gobtools.DecodeSimple[int32](buf, &val10)
	if err != nil {
		return err
	}
	if val10 > 0 {
		r.ModeInfos = make(map[string]ModeInfo, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			var k string
			var v ModeInfo
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			if err = v.Decode(buf); err != nil {
				return err
			}
			r.ModeInfos[k] = v
		}
	}

	return err
}

var aconfigPropagatingDeclarationsInfoGobRegId int16

func (r aconfigPropagatingDeclarationsInfo) GetTypeId() int16 {
	return aconfigPropagatingDeclarationsInfoGobRegId
}
