// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ComplianceMetadataInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ComplianceMetadataInfo) })
}

func (r ComplianceMetadataInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.properties))); err != nil {
		return err
	}
	for k, v := range r.properties {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = gobtools.EncodeString(buf, v); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.filesContained))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.filesContained); val1++ {
		if err = gobtools.EncodeString(buf, r.filesContained[val1]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.prebuiltFilesCopied))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(r.prebuiltFilesCopied); val2++ {
		if err = gobtools.EncodeString(buf, r.prebuiltFilesCopied[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.platformGeneratedFiles))); err != nil {
		return err
	}
	for val3 := 0; val3 < len(r.platformGeneratedFiles); val3++ {
		if err = gobtools.EncodeString(buf, r.platformGeneratedFiles[val3]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.productCopyFiles))); err != nil {
		return err
	}
	for val4 := 0; val4 < len(r.productCopyFiles); val4++ {
		if err = gobtools.EncodeString(buf, r.productCopyFiles[val4]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.kernelModuleCopyFiles))); err != nil {
		return err
	}
	for val5 := 0; val5 < len(r.kernelModuleCopyFiles); val5++ {
		if err = gobtools.EncodeString(buf, r.kernelModuleCopyFiles[val5]); err != nil {
			return err
		}
	}
	return err
}

func (r *ComplianceMetadataInfo) Decode(buf *bytes.Reader) error {
	var err error

	var val1 int32
	err = gobtools.DecodeSimple[int32](buf, &val1)
	if err != nil {
		return err
	}
	if val1 > 0 {
		r.properties = make(map[string]string, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v string
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			err = gobtools.DecodeString(buf, &v)
			if err != nil {
				return err
			}
			r.properties[k] = v
		}
	}

	var val6 int32
	err = gobtools.DecodeSimple[int32](buf, &val6)
	if err != nil {
		return err
	}
	if val6 > 0 {
		r.filesContained = make([]string, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			err = gobtools.DecodeString(buf, &r.filesContained[val7])
			if err != nil {
				return err
			}
		}
	}

	var val10 int32
	err = gobtools.DecodeSimple[int32](buf, &val10)
	if err != nil {
		return err
	}
	if val10 > 0 {
		r.prebuiltFilesCopied = make([]string, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			err = gobtools.DecodeString(buf, &r.prebuiltFilesCopied[val11])
			if err != nil {
				return err
			}
		}
	}

	var val14 int32
	err = gobtools.DecodeSimple[int32](buf, &val14)
	if err != nil {
		return err
	}
	if val14 > 0 {
		r.platformGeneratedFiles = make([]string, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			err = gobtools.DecodeString(buf, &r.platformGeneratedFiles[val15])
			if err != nil {
				return err
			}
		}
	}

	var val18 int32
	err = gobtools.DecodeSimple[int32](buf, &val18)
	if err != nil {
		return err
	}
	if val18 > 0 {
		r.productCopyFiles = make([]string, val18)
		for val19 := 0; val19 < int(val18); val19++ {
			err = gobtools.DecodeString(buf, &r.productCopyFiles[val19])
			if err != nil {
				return err
			}
		}
	}

	var val22 int32
	err = gobtools.DecodeSimple[int32](buf, &val22)
	if err != nil {
		return err
	}
	if val22 > 0 {
		r.kernelModuleCopyFiles = make([]string, val22)
		for val23 := 0; val23 < int(val22); val23++ {
			err = gobtools.DecodeString(buf, &r.kernelModuleCopyFiles[val23])
			if err != nil {
				return err
			}
		}
	}

	return err
}

var ComplianceMetadataInfoGobRegId int16

func (r ComplianceMetadataInfo) GetTypeId() int16 {
	return ComplianceMetadataInfoGobRegId
}
