// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	DistGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(Dist) })
	InstallFilesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(InstallFilesInfo) })
	ModuleBuildTargetsInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleBuildTargetsInfo) })
	CommonModuleInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CommonModuleInfo) })
	ApiLevelOrPlatformGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ApiLevelOrPlatform) })
	HostToolProviderInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(HostToolProviderInfo) })
	katiInstallGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(katiInstall) })
	extraFilesZipGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(extraFilesZip) })
	OutputFilesInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(OutputFilesInfo) })
}

func (r Dist) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.Targets))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.Targets); val1++ {
		if err = gobtools.EncodeString(buf, r.Targets[val1]); err != nil {
			return err
		}
	}

	val2 := r.Dest == nil
	if err = gobtools.EncodeSimple(buf, val2); err != nil {
		return err
	}
	if !val2 {
		if err = gobtools.EncodeString(buf, (*r.Dest)); err != nil {
			return err
		}
	}

	val3 := r.Dir == nil
	if err = gobtools.EncodeSimple(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = gobtools.EncodeString(buf, (*r.Dir)); err != nil {
			return err
		}
	}

	val4 := r.Suffix == nil
	if err = gobtools.EncodeSimple(buf, val4); err != nil {
		return err
	}
	if !val4 {
		if err = gobtools.EncodeString(buf, (*r.Suffix)); err != nil {
			return err
		}
	}

	val5 := r.Append_artifact_with_product == nil
	if err = gobtools.EncodeSimple(buf, val5); err != nil {
		return err
	}
	if !val5 {
		if err = gobtools.EncodeSimple(buf, (*r.Append_artifact_with_product)); err != nil {
			return err
		}
	}

	val6 := r.Prepend_artifact_with_product == nil
	if err = gobtools.EncodeSimple(buf, val6); err != nil {
		return err
	}
	if !val6 {
		if err = gobtools.EncodeSimple(buf, (*r.Prepend_artifact_with_product)); err != nil {
			return err
		}
	}

	val7 := r.Tag == nil
	if err = gobtools.EncodeSimple(buf, val7); err != nil {
		return err
	}
	if !val7 {
		if err = gobtools.EncodeString(buf, (*r.Tag)); err != nil {
			return err
		}
	}
	return err
}

func (r *Dist) Decode(buf *bytes.Reader) error {
	var err error

	var val2 int32
	err = gobtools.DecodeSimple[int32](buf, &val2)
	if err != nil {
		return err
	}
	if val2 > 0 {
		r.Targets = make([]string, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			err = gobtools.DecodeString(buf, &r.Targets[val3])
			if err != nil {
				return err
			}
		}
	}

	var val6 bool
	if err = gobtools.DecodeSimple(buf, &val6); err != nil {
		return err
	}
	if !val6 {
		var val5 string
		err = gobtools.DecodeString(buf, &val5)
		if err != nil {
			return err
		}
		r.Dest = &val5
	}

	var val9 bool
	if err = gobtools.DecodeSimple(buf, &val9); err != nil {
		return err
	}
	if !val9 {
		var val8 string
		err = gobtools.DecodeString(buf, &val8)
		if err != nil {
			return err
		}
		r.Dir = &val8
	}

	var val12 bool
	if err = gobtools.DecodeSimple(buf, &val12); err != nil {
		return err
	}
	if !val12 {
		var val11 string
		err = gobtools.DecodeString(buf, &val11)
		if err != nil {
			return err
		}
		r.Suffix = &val11
	}

	var val15 bool
	if err = gobtools.DecodeSimple(buf, &val15); err != nil {
		return err
	}
	if !val15 {
		var val14 bool
		err = gobtools.DecodeSimple[bool](buf, &val14)
		if err != nil {
			return err
		}
		r.Append_artifact_with_product = &val14
	}

	var val18 bool
	if err = gobtools.DecodeSimple(buf, &val18); err != nil {
		return err
	}
	if !val18 {
		var val17 bool
		err = gobtools.DecodeSimple[bool](buf, &val17)
		if err != nil {
			return err
		}
		r.Prepend_artifact_with_product = &val17
	}

	var val21 bool
	if err = gobtools.DecodeSimple(buf, &val21); err != nil {
		return err
	}
	if !val21 {
		var val20 string
		err = gobtools.DecodeString(buf, &val20)
		if err != nil {
			return err
		}
		r.Tag = &val20
	}

	return err
}

var DistGobRegId int16

func (r Dist) GetTypeId() int16 {
	return DistGobRegId
}

func (r InstallFilesInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.InstallFiles))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.InstallFiles); val1++ {
		if err = r.InstallFiles[val1].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.CheckbuildFiles))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(r.CheckbuildFiles); val2++ {
		if err = gobtools.EncodeInterface(buf, r.CheckbuildFiles[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, r.UncheckedModule); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.PackagingSpecs))); err != nil {
		return err
	}
	for val3 := 0; val3 < len(r.PackagingSpecs); val3++ {
		if err = r.PackagingSpecs[val3].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.KatiInstalls))); err != nil {
		return err
	}
	for val4 := 0; val4 < len(r.KatiInstalls); val4++ {
		if err = r.KatiInstalls[val4].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.KatiSymlinks))); err != nil {
		return err
	}
	for val5 := 0; val5 < len(r.KatiSymlinks); val5++ {
		if err = r.KatiSymlinks[val5].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.TestData))); err != nil {
		return err
	}
	for val6 := 0; val6 < len(r.TestData); val6++ {
		if err = r.TestData[val6].Encode(buf); err != nil {
			return err
		}
	}

	if err = r.TransitivePackagingSpecs.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.LicenseMetadataFile); err != nil {
		return err
	}

	if err = r.TransitiveInstallFiles.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.KatiInitRcInstalls))); err != nil {
		return err
	}
	for val7 := 0; val7 < len(r.KatiInitRcInstalls); val7++ {
		if err = r.KatiInitRcInstalls[val7].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.KatiVintfInstalls))); err != nil {
		return err
	}
	for val8 := 0; val8 < len(r.KatiVintfInstalls); val8++ {
		if err = r.KatiVintfInstalls[val8].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.InitRcPaths))); err != nil {
		return err
	}
	for val9 := 0; val9 < len(r.InitRcPaths); val9++ {
		if err = gobtools.EncodeInterface(buf, r.InitRcPaths[val9]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.VintfFragmentsPaths))); err != nil {
		return err
	}
	for val10 := 0; val10 < len(r.VintfFragmentsPaths); val10++ {
		if err = gobtools.EncodeInterface(buf, r.VintfFragmentsPaths[val10]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.InstalledInitRcPaths))); err != nil {
		return err
	}
	for val11 := 0; val11 < len(r.InstalledInitRcPaths); val11++ {
		if err = r.InstalledInitRcPaths[val11].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.InstalledVintfFragmentsPaths))); err != nil {
		return err
	}
	for val12 := 0; val12 < len(r.InstalledVintfFragmentsPaths); val12++ {
		if err = r.InstalledVintfFragmentsPaths[val12].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.DistFiles))); err != nil {
		return err
	}
	for k, v := range r.DistFiles {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = gobtools.EncodeSimple(buf, int32(len(v))); err != nil {
			return err
		}
		for val13 := 0; val13 < len(v); val13++ {
			if err = gobtools.EncodeInterface(buf, v[val13]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *InstallFilesInfo) Decode(buf *bytes.Reader) error {
	var err error

	var val3 int32
	err = gobtools.DecodeSimple[int32](buf, &val3)
	if err != nil {
		return err
	}
	if val3 > 0 {
		r.InstallFiles = make([]InstallPath, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if err = r.InstallFiles[val4].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val8 int32
	err = gobtools.DecodeSimple[int32](buf, &val8)
	if err != nil {
		return err
	}
	if val8 > 0 {
		r.CheckbuildFiles = make([]Path, val8)
		for val9 := 0; val9 < int(val8); val9++ {
			if val11, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val11 == nil {
				r.CheckbuildFiles[val9] = nil
			} else {
				r.CheckbuildFiles[val9] = val11.(Path)
			}
		}
	}

	err = gobtools.DecodeSimple[bool](buf, &r.UncheckedModule)
	if err != nil {
		return err
	}

	var val14 int32
	err = gobtools.DecodeSimple[int32](buf, &val14)
	if err != nil {
		return err
	}
	if val14 > 0 {
		r.PackagingSpecs = make([]PackagingSpec, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			if err = r.PackagingSpecs[val15].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val19 int32
	err = gobtools.DecodeSimple[int32](buf, &val19)
	if err != nil {
		return err
	}
	if val19 > 0 {
		r.KatiInstalls = make([]katiInstall, val19)
		for val20 := 0; val20 < int(val19); val20++ {
			if err = r.KatiInstalls[val20].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val24 int32
	err = gobtools.DecodeSimple[int32](buf, &val24)
	if err != nil {
		return err
	}
	if val24 > 0 {
		r.KatiSymlinks = make([]katiInstall, val24)
		for val25 := 0; val25 < int(val24); val25++ {
			if err = r.KatiSymlinks[val25].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val28 int32
	err = gobtools.DecodeSimple[int32](buf, &val28)
	if err != nil {
		return err
	}
	if val28 > 0 {
		r.TestData = make([]DataPath, val28)
		for val29 := 0; val29 < int(val28); val29++ {
			if err = r.TestData[val29].Decode(buf); err != nil {
				return err
			}
		}
	}

	if err = r.TransitivePackagingSpecs.Decode(buf); err != nil {
		return err
	}

	if val33, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val33 == nil {
		r.LicenseMetadataFile = nil
	} else {
		r.LicenseMetadataFile = val33.(WritablePath)
	}

	if err = r.TransitiveInstallFiles.Decode(buf); err != nil {
		return err
	}

	var val37 int32
	err = gobtools.DecodeSimple[int32](buf, &val37)
	if err != nil {
		return err
	}
	if val37 > 0 {
		r.KatiInitRcInstalls = make([]katiInstall, val37)
		for val38 := 0; val38 < int(val37); val38++ {
			if err = r.KatiInitRcInstalls[val38].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val42 int32
	err = gobtools.DecodeSimple[int32](buf, &val42)
	if err != nil {
		return err
	}
	if val42 > 0 {
		r.KatiVintfInstalls = make([]katiInstall, val42)
		for val43 := 0; val43 < int(val42); val43++ {
			if err = r.KatiVintfInstalls[val43].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val47 int32
	err = gobtools.DecodeSimple[int32](buf, &val47)
	if err != nil {
		return err
	}
	if val47 > 0 {
		r.InitRcPaths = make([]Path, val47)
		for val48 := 0; val48 < int(val47); val48++ {
			if val50, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val50 == nil {
				r.InitRcPaths[val48] = nil
			} else {
				r.InitRcPaths[val48] = val50.(Path)
			}
		}
	}

	var val53 int32
	err = gobtools.DecodeSimple[int32](buf, &val53)
	if err != nil {
		return err
	}
	if val53 > 0 {
		r.VintfFragmentsPaths = make([]Path, val53)
		for val54 := 0; val54 < int(val53); val54++ {
			if val56, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val56 == nil {
				r.VintfFragmentsPaths[val54] = nil
			} else {
				r.VintfFragmentsPaths[val54] = val56.(Path)
			}
		}
	}

	var val59 int32
	err = gobtools.DecodeSimple[int32](buf, &val59)
	if err != nil {
		return err
	}
	if val59 > 0 {
		r.InstalledInitRcPaths = make([]InstallPath, val59)
		for val60 := 0; val60 < int(val59); val60++ {
			if err = r.InstalledInitRcPaths[val60].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val64 int32
	err = gobtools.DecodeSimple[int32](buf, &val64)
	if err != nil {
		return err
	}
	if val64 > 0 {
		r.InstalledVintfFragmentsPaths = make([]InstallPath, val64)
		for val65 := 0; val65 < int(val64); val65++ {
			if err = r.InstalledVintfFragmentsPaths[val65].Decode(buf); err != nil {
				return err
			}
		}
	}

	var val68 int32
	err = gobtools.DecodeSimple[int32](buf, &val68)
	if err != nil {
		return err
	}
	if val68 > 0 {
		r.DistFiles = make(map[string]Paths, val68)
		for val69 := 0; val69 < int(val68); val69++ {
			var k string
			var v Paths
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val73 int32
			err = gobtools.DecodeSimple[int32](buf, &val73)
			if err != nil {
				return err
			}
			if val73 > 0 {
				v = make([]Path, val73)
				for val74 := 0; val74 < int(val73); val74++ {
					if val76, err := gobtools.DecodeInterface(buf); err != nil {
						return err
					} else if val76 == nil {
						v[val74] = nil
					} else {
						v[val74] = val76.(Path)
					}
				}
			}
			r.DistFiles[k] = v
		}
	}

	return err
}

var InstallFilesInfoGobRegId int16

func (r InstallFilesInfo) GetTypeId() int16 {
	return InstallFilesInfoGobRegId
}

func (r ModuleBuildTargetsInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.InstallTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.CheckbuildTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.BlueprintDir); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.AllDeps))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.AllDeps); val1++ {
		if err = gobtools.EncodeInterface(buf, r.AllDeps[val1]); err != nil {
			return err
		}
	}
	return err
}

func (r *ModuleBuildTargetsInfo) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.InstallTarget = nil
	} else {
		r.InstallTarget = val2.(WritablePath)
	}

	if val4, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val4 == nil {
		r.CheckbuildTarget = nil
	} else {
		r.CheckbuildTarget = val4.(WritablePath)
	}

	err = gobtools.DecodeString(buf, &r.BlueprintDir)
	if err != nil {
		return err
	}

	var val8 int32
	err = gobtools.DecodeSimple[int32](buf, &val8)
	if err != nil {
		return err
	}
	if val8 > 0 {
		r.AllDeps = make([]Path, val8)
		for val9 := 0; val9 < int(val8); val9++ {
			if val11, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val11 == nil {
				r.AllDeps[val9] = nil
			} else {
				r.AllDeps[val9] = val11.(Path)
			}
		}
	}

	return err
}

var ModuleBuildTargetsInfoGobRegId int16

func (r ModuleBuildTargetsInfo) GetTypeId() int16 {
	return ModuleBuildTargetsInfoGobRegId
}

func (r CommonModuleInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, r.Enabled); err != nil {
		return err
	}

	if err = r.Target.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.SkipAndroidMkProcessing); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.BaseModuleName); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.CanHaveApexVariants); err != nil {
		return err
	}

	if err = r.MinSdkVersion.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.SdkVersion); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.NotInPlatform); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.UninstallableApexPlatformVariant); err != nil {
		return err
	}

	if err = r.MinSdkVersionSupported.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.ModuleWithMinSdkVersionCheck); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.IsInstallableToApex); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.HideFromMake); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.SkipInstall); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.IsStubsModule); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.Host); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.IsApexModule); err != nil {
		return err
	}

	val1 := r.PrimaryLicensesProperty == nil
	if err = gobtools.EncodeSimple(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.PrimaryLicensesProperty).Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.Owner); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.Vendor); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.Proprietary); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.SocSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.ProductSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.SystemExtSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.DeviceSpecific); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.UseGenericConfig); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.NoFullInstall); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.InVendorRamdisk); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.ExemptFromRequiredApplicableLicensesProperty); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.RequiredModuleNames))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(r.RequiredModuleNames); val2++ {
		if err = gobtools.EncodeString(buf, r.RequiredModuleNames[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.HostRequiredModuleNames))); err != nil {
		return err
	}
	for val3 := 0; val3 < len(r.HostRequiredModuleNames); val3++ {
		if err = gobtools.EncodeString(buf, r.HostRequiredModuleNames[val3]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.TargetRequiredModuleNames))); err != nil {
		return err
	}
	for val4 := 0; val4 < len(r.TargetRequiredModuleNames); val4++ {
		if err = gobtools.EncodeString(buf, r.TargetRequiredModuleNames[val4]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.VintfFragmentModuleNames))); err != nil {
		return err
	}
	for val5 := 0; val5 < len(r.VintfFragmentModuleNames); val5++ {
		if err = gobtools.EncodeString(buf, r.VintfFragmentModuleNames[val5]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.Dists))); err != nil {
		return err
	}
	for val6 := 0; val6 < len(r.Dists); val6++ {
		if err = r.Dists[val6].Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, r.ExportedToMake); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Team); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.PartitionTag); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.ApexAvailable))); err != nil {
		return err
	}
	for val7 := 0; val7 < len(r.ApexAvailable); val7++ {
		if err = gobtools.EncodeString(buf, r.ApexAvailable[val7]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.ApexAvailableFor))); err != nil {
		return err
	}
	for val8 := 0; val8 < len(r.ApexAvailableFor); val8++ {
		if err = gobtools.EncodeString(buf, r.ApexAvailableFor[val8]); err != nil {
			return err
		}
	}

	if err = r.ImageVariation.Encode(buf); err != nil {
		return err
	}
	return err
}

func (r *CommonModuleInfo) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeSimple[bool](buf, &r.Enabled)
	if err != nil {
		return err
	}

	if err = r.Target.Decode(buf); err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.SkipAndroidMkProcessing)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.BaseModuleName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.CanHaveApexVariants)
	if err != nil {
		return err
	}

	if err = r.MinSdkVersion.Decode(buf); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.SdkVersion)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.NotInPlatform)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.UninstallableApexPlatformVariant)
	if err != nil {
		return err
	}

	if err = r.MinSdkVersionSupported.Decode(buf); err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.ModuleWithMinSdkVersionCheck)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.IsInstallableToApex)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.HideFromMake)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.SkipInstall)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.IsStubsModule)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.Host)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.IsApexModule)
	if err != nil {
		return err
	}

	var val19 bool
	if err = gobtools.DecodeSimple(buf, &val19); err != nil {
		return err
	}
	if !val19 {
		var val18 applicableLicensesProperty
		if err = val18.Decode(buf); err != nil {
			return err
		}
		r.PrimaryLicensesProperty = &val18
	}

	err = gobtools.DecodeString(buf, &r.Owner)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.Vendor)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.Proprietary)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.SocSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.ProductSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.SystemExtSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.DeviceSpecific)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.UseGenericConfig)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.NoFullInstall)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.InVendorRamdisk)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.ExemptFromRequiredApplicableLicensesProperty)
	if err != nil {
		return err
	}

	var val33 int32
	err = gobtools.DecodeSimple[int32](buf, &val33)
	if err != nil {
		return err
	}
	if val33 > 0 {
		r.RequiredModuleNames = make([]string, val33)
		for val34 := 0; val34 < int(val33); val34++ {
			err = gobtools.DecodeString(buf, &r.RequiredModuleNames[val34])
			if err != nil {
				return err
			}
		}
	}

	var val37 int32
	err = gobtools.DecodeSimple[int32](buf, &val37)
	if err != nil {
		return err
	}
	if val37 > 0 {
		r.HostRequiredModuleNames = make([]string, val37)
		for val38 := 0; val38 < int(val37); val38++ {
			err = gobtools.DecodeString(buf, &r.HostRequiredModuleNames[val38])
			if err != nil {
				return err
			}
		}
	}

	var val41 int32
	err = gobtools.DecodeSimple[int32](buf, &val41)
	if err != nil {
		return err
	}
	if val41 > 0 {
		r.TargetRequiredModuleNames = make([]string, val41)
		for val42 := 0; val42 < int(val41); val42++ {
			err = gobtools.DecodeString(buf, &r.TargetRequiredModuleNames[val42])
			if err != nil {
				return err
			}
		}
	}

	var val45 int32
	err = gobtools.DecodeSimple[int32](buf, &val45)
	if err != nil {
		return err
	}
	if val45 > 0 {
		r.VintfFragmentModuleNames = make([]string, val45)
		for val46 := 0; val46 < int(val45); val46++ {
			err = gobtools.DecodeString(buf, &r.VintfFragmentModuleNames[val46])
			if err != nil {
				return err
			}
		}
	}

	var val49 int32
	err = gobtools.DecodeSimple[int32](buf, &val49)
	if err != nil {
		return err
	}
	if val49 > 0 {
		r.Dists = make([]Dist, val49)
		for val50 := 0; val50 < int(val49); val50++ {
			if err = r.Dists[val50].Decode(buf); err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeSimple[bool](buf, &r.ExportedToMake)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Team)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.PartitionTag)
	if err != nil {
		return err
	}

	var val56 int32
	err = gobtools.DecodeSimple[int32](buf, &val56)
	if err != nil {
		return err
	}
	if val56 > 0 {
		r.ApexAvailable = make([]string, val56)
		for val57 := 0; val57 < int(val56); val57++ {
			err = gobtools.DecodeString(buf, &r.ApexAvailable[val57])
			if err != nil {
				return err
			}
		}
	}

	var val60 int32
	err = gobtools.DecodeSimple[int32](buf, &val60)
	if err != nil {
		return err
	}
	if val60 > 0 {
		r.ApexAvailableFor = make([]string, val60)
		for val61 := 0; val61 < int(val60); val61++ {
			err = gobtools.DecodeString(buf, &r.ApexAvailableFor[val61])
			if err != nil {
				return err
			}
		}
	}

	if err = r.ImageVariation.Decode(buf); err != nil {
		return err
	}

	return err
}

var CommonModuleInfoGobRegId int16

func (r CommonModuleInfo) GetTypeId() int16 {
	return CommonModuleInfoGobRegId
}

func (r ApiLevelOrPlatform) Encode(buf *bytes.Buffer) error {
	var err error

	val1 := r.ApiLevel == nil
	if err = gobtools.EncodeSimple(buf, val1); err != nil {
		return err
	}
	if !val1 {
		if err = (*r.ApiLevel).Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, r.IsPlatform); err != nil {
		return err
	}
	return err
}

func (r *ApiLevelOrPlatform) Decode(buf *bytes.Reader) error {
	var err error

	var val2 bool
	if err = gobtools.DecodeSimple(buf, &val2); err != nil {
		return err
	}
	if !val2 {
		var val1 ApiLevel
		if err = val1.Decode(buf); err != nil {
			return err
		}
		r.ApiLevel = &val1
	}

	err = gobtools.DecodeSimple[bool](buf, &r.IsPlatform)
	if err != nil {
		return err
	}

	return err
}

var ApiLevelOrPlatformGobRegId int16

func (r ApiLevelOrPlatform) GetTypeId() int16 {
	return ApiLevelOrPlatformGobRegId
}

func (r HostToolProviderInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = r.HostToolPath.Encode(buf); err != nil {
		return err
	}
	return err
}

func (r *HostToolProviderInfo) Decode(buf *bytes.Reader) error {
	var err error

	if err = r.HostToolPath.Decode(buf); err != nil {
		return err
	}

	return err
}

var HostToolProviderInfoGobRegId int16

func (r HostToolProviderInfo) GetTypeId() int16 {
	return HostToolProviderInfoGobRegId
}

func (r katiInstall) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.from); err != nil {
		return err
	}

	if err = r.to.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.implicitDeps))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.implicitDeps); val1++ {
		if err = gobtools.EncodeInterface(buf, r.implicitDeps[val1]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.orderOnlyDeps))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(r.orderOnlyDeps); val2++ {
		if err = gobtools.EncodeInterface(buf, r.orderOnlyDeps[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, r.executable); err != nil {
		return err
	}

	val3 := r.extraFiles == nil
	if err = gobtools.EncodeSimple(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = (*r.extraFiles).Encode(buf); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.absFrom); err != nil {
		return err
	}
	return err
}

func (r *katiInstall) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.from = nil
	} else {
		r.from = val2.(Path)
	}

	if err = r.to.Decode(buf); err != nil {
		return err
	}

	var val6 int32
	err = gobtools.DecodeSimple[int32](buf, &val6)
	if err != nil {
		return err
	}
	if val6 > 0 {
		r.implicitDeps = make([]Path, val6)
		for val7 := 0; val7 < int(val6); val7++ {
			if val9, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val9 == nil {
				r.implicitDeps[val7] = nil
			} else {
				r.implicitDeps[val7] = val9.(Path)
			}
		}
	}

	var val12 int32
	err = gobtools.DecodeSimple[int32](buf, &val12)
	if err != nil {
		return err
	}
	if val12 > 0 {
		r.orderOnlyDeps = make([]Path, val12)
		for val13 := 0; val13 < int(val12); val13++ {
			if val15, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val15 == nil {
				r.orderOnlyDeps[val13] = nil
			} else {
				r.orderOnlyDeps[val13] = val15.(Path)
			}
		}
	}

	err = gobtools.DecodeSimple[bool](buf, &r.executable)
	if err != nil {
		return err
	}

	var val18 bool
	if err = gobtools.DecodeSimple(buf, &val18); err != nil {
		return err
	}
	if !val18 {
		var val17 extraFilesZip
		if err = val17.Decode(buf); err != nil {
			return err
		}
		r.extraFiles = &val17
	}

	err = gobtools.DecodeString(buf, &r.absFrom)
	if err != nil {
		return err
	}

	return err
}

var katiInstallGobRegId int16

func (r katiInstall) GetTypeId() int16 {
	return katiInstallGobRegId
}

func (r extraFilesZip) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.zip); err != nil {
		return err
	}

	if err = r.dir.Encode(buf); err != nil {
		return err
	}
	return err
}

func (r *extraFilesZip) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.zip = nil
	} else {
		r.zip = val2.(Path)
	}

	if err = r.dir.Decode(buf); err != nil {
		return err
	}

	return err
}

var extraFilesZipGobRegId int16

func (r extraFilesZip) GetTypeId() int16 {
	return extraFilesZipGobRegId
}

func (r OutputFilesInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.DefaultOutputFiles))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.DefaultOutputFiles); val1++ {
		if err = gobtools.EncodeInterface(buf, r.DefaultOutputFiles[val1]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.TaggedOutputFiles))); err != nil {
		return err
	}
	for k, v := range r.TaggedOutputFiles {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = gobtools.EncodeSimple(buf, int32(len(v))); err != nil {
			return err
		}
		for val2 := 0; val2 < len(v); val2++ {
			if err = gobtools.EncodeInterface(buf, v[val2]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *OutputFilesInfo) Decode(buf *bytes.Reader) error {
	var err error

	var val3 int32
	err = gobtools.DecodeSimple[int32](buf, &val3)
	if err != nil {
		return err
	}
	if val3 > 0 {
		r.DefaultOutputFiles = make([]Path, val3)
		for val4 := 0; val4 < int(val3); val4++ {
			if val6, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val6 == nil {
				r.DefaultOutputFiles[val4] = nil
			} else {
				r.DefaultOutputFiles[val4] = val6.(Path)
			}
		}
	}

	var val7 int32
	err = gobtools.DecodeSimple[int32](buf, &val7)
	if err != nil {
		return err
	}
	if val7 > 0 {
		r.TaggedOutputFiles = make(map[string]Paths, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			var k string
			var v Paths
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val12 int32
			err = gobtools.DecodeSimple[int32](buf, &val12)
			if err != nil {
				return err
			}
			if val12 > 0 {
				v = make([]Path, val12)
				for val13 := 0; val13 < int(val12); val13++ {
					if val15, err := gobtools.DecodeInterface(buf); err != nil {
						return err
					} else if val15 == nil {
						v[val13] = nil
					} else {
						v[val13] = val15.(Path)
					}
				}
			}
			r.TaggedOutputFiles[k] = v
		}
	}

	return err
}

var OutputFilesInfoGobRegId int16

func (r OutputFilesInfo) GetTypeId() int16 {
	return OutputFilesInfoGobRegId
}
