// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	ModulePhonyInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModulePhonyInfo) })
}

func (r ModulePhonyInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, int32(len(r.Phonies))); err != nil {
		return err
	}
	for k, v := range r.Phonies {
		if err = gobtools.EncodeString(buf, k); err != nil {
			return err
		}
		if err = gobtools.EncodeSimple(buf, int32(len(v))); err != nil {
			return err
		}
		for val1 := 0; val1 < len(v); val1++ {
			if err = gobtools.EncodeInterface(buf, v[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r *ModulePhonyInfo) Decode(buf *bytes.Reader) error {
	var err error

	var val1 int32
	err = gobtools.DecodeSimple[int32](buf, &val1)
	if err != nil {
		return err
	}
	if val1 > 0 {
		r.Phonies = make(map[string]Paths, val1)
		for val2 := 0; val2 < int(val1); val2++ {
			var k string
			var v Paths
			err = gobtools.DecodeString(buf, &k)
			if err != nil {
				return err
			}
			var val6 int32
			err = gobtools.DecodeSimple[int32](buf, &val6)
			if err != nil {
				return err
			}
			if val6 > 0 {
				v = make([]Path, val6)
				for val7 := 0; val7 < int(val6); val7++ {
					if val9, err := gobtools.DecodeInterface(buf); err != nil {
						return err
					} else if val9 == nil {
						v[val7] = nil
					} else {
						v[val7] = val9.(Path)
					}
				}
			}
			r.Phonies[k] = v
		}
	}

	return err
}

var ModulePhonyInfoGobRegId int16

func (r ModulePhonyInfo) GetTypeId() int16 {
	return ModulePhonyInfoGobRegId
}
