// Code generated by go run gob_gen.go; DO NOT EDIT.

package cc

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	SharedLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SharedLibraryInfo) })
	StaticLibraryInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(StaticLibraryInfo) })
	ImplementationDepInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ImplementationDepInfo) })
}

func (r SharedLibraryInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.SharedLibrary); err != nil {
		return err
	}

	if err = r.Target.Encode(buf); err != nil {
		return err
	}

	if err = r.TableOfContents.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.IsStubs); err != nil {
		return err
	}

	if err = r.ImplementationDeps.EncodeString(buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibrariesForOrdering.EncodeInterface(buf); err != nil {
		return err
	}
	return err
}

func (r *SharedLibraryInfo) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.SharedLibrary = nil
	} else {
		r.SharedLibrary = val2.(android.Path)
	}

	if err = r.Target.Decode(buf); err != nil {
		return err
	}

	if err = r.TableOfContents.Decode(buf); err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.IsStubs)
	if err != nil {
		return err
	}

	if err = r.ImplementationDeps.DecodeString(buf); err != nil {
		return err
	}

	if err = r.TransitiveStaticLibrariesForOrdering.DecodeInterface(buf); err != nil {
		return err
	}

	return err
}

var SharedLibraryInfoGobRegId int16

func (r SharedLibraryInfo) GetTypeId() int16 {
	return SharedLibraryInfoGobRegId
}

func (r StaticLibraryInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.StaticLibrary); err != nil {
		return err
	}

	if err = r.Objects.Encode(buf); err != nil {
		return err
	}

	if err = r.ReuseObjects.Encode(buf); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.WholeStaticLibsFromPrebuilts))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.WholeStaticLibsFromPrebuilts); val1++ {
		if err = gobtools.EncodeInterface(buf, r.WholeStaticLibsFromPrebuilts[val1]); err != nil {
			return err
		}
	}

	if err = r.TransitiveStaticLibrariesForOrdering.EncodeInterface(buf); err != nil {
		return err
	}
	return err
}

func (r *StaticLibraryInfo) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.StaticLibrary = nil
	} else {
		r.StaticLibrary = val2.(android.Path)
	}

	if err = r.Objects.Decode(buf); err != nil {
		return err
	}

	if err = r.ReuseObjects.Decode(buf); err != nil {
		return err
	}

	var val7 int32
	err = gobtools.DecodeSimple[int32](buf, &val7)
	if err != nil {
		return err
	}
	if val7 > 0 {
		r.WholeStaticLibsFromPrebuilts = make([]android.Path, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			if val10, err := gobtools.DecodeInterface(buf); err != nil {
				return err
			} else if val10 == nil {
				r.WholeStaticLibsFromPrebuilts[val8] = nil
			} else {
				r.WholeStaticLibsFromPrebuilts[val8] = val10.(android.Path)
			}
		}
	}

	if err = r.TransitiveStaticLibrariesForOrdering.DecodeInterface(buf); err != nil {
		return err
	}

	return err
}

var StaticLibraryInfoGobRegId int16

func (r StaticLibraryInfo) GetTypeId() int16 {
	return StaticLibraryInfoGobRegId
}

func (r ImplementationDepInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = r.ImplementationDeps.EncodeInterface(buf); err != nil {
		return err
	}
	return err
}

func (r *ImplementationDepInfo) Decode(buf *bytes.Reader) error {
	var err error

	if err = r.ImplementationDeps.DecodeInterface(buf); err != nil {
		return err
	}

	return err
}

var ImplementationDepInfoGobRegId int16

func (r ImplementationDepInfo) GetTypeId() int16 {
	return ImplementationDepInfoGobRegId
}
