// Code generated by go run gob_gen.go; DO NOT EDIT.

package java

import (
	"android/soong/android"
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	LintInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(LintInfo) })
}

func (r LintInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.HTML); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.Text); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.XML); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, r.ReferenceBaseline); err != nil {
		return err
	}

	if err = r.TransitiveHTML.EncodeInterface(buf); err != nil {
		return err
	}

	if err = r.TransitiveText.EncodeInterface(buf); err != nil {
		return err
	}

	if err = r.TransitiveXML.EncodeInterface(buf); err != nil {
		return err
	}

	if err = r.TransitiveBaseline.EncodeInterface(buf); err != nil {
		return err
	}
	return err
}

func (r *LintInfo) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.HTML = nil
	} else {
		r.HTML = val2.(android.Path)
	}

	if val4, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val4 == nil {
		r.Text = nil
	} else {
		r.Text = val4.(android.Path)
	}

	if val6, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val6 == nil {
		r.XML = nil
	} else {
		r.XML = val6.(android.Path)
	}

	if val8, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val8 == nil {
		r.ReferenceBaseline = nil
	} else {
		r.ReferenceBaseline = val8.(android.Path)
	}

	if err = r.TransitiveHTML.DecodeInterface(buf); err != nil {
		return err
	}

	if err = r.TransitiveText.DecodeInterface(buf); err != nil {
		return err
	}

	if err = r.TransitiveXML.DecodeInterface(buf); err != nil {
		return err
	}

	if err = r.TransitiveBaseline.DecodeInterface(buf); err != nil {
		return err
	}

	return err
}

var LintInfoGobRegId int16

func (r LintInfo) GetTypeId() int16 {
	return LintInfoGobRegId
}
