// Code generated by go run gob_gen.go; DO NOT EDIT.

package bloaty

import (
	"android/soong/android"
	"bytes"
	"fmt"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
	"reflect"
)

// begin of bloaty.go
func init() {
	measuredFilesGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(measuredFiles) })
}

func (r measuredFiles) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if r.paths == nil {
		if err = gobtools.EncodeInt(buf, -1); err != nil {
			return err
		}
	} else {
		if err = gobtools.EncodeInt(buf, len(r.paths)); err != nil {
			return err
		}
		for val1 := 0; val1 < len(r.paths); val1++ {
			if err = gobtools.EncodeInterface(ctx, buf, r.paths[val1]); err != nil {
				return err
			}
		}
	}
	return err
}

func (r measuredFiles) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":bloaty.measuredFiles")
	hasher.WriteInt(1)
	hasher.WriteString(":.[]android.WritablePath")
	hasher.WriteInt(len(r.paths))
	for val1 := 0; val1 < len(r.paths); val1++ {
		hasher.WriteString(":bloaty.android.WritablePath")
		val2 := r.paths[val1] == nil
		if val2 {
			hasher.WriteByte(0)
		} else {
			if v := reflect.ValueOf(r.paths[val1]); v.Kind() == reflect.Ptr {
				if v.IsNil() {
					panic(fmt.Errorf("nil pointer is not supported in interface"))
				} else {
					val3 := r.paths[val1] == nil
					if val3 {
						hasher.WriteByte(0)
					} else {
						val4 := func(hasher *proptools.Hasher) error { return r.paths[val1].(proptools.CustomHash).CustomHash(hasher) }
						if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val4); err != nil {
							return err
						}
					}
				}
			} else {
				r.paths[val1].(proptools.CustomHash).CustomHash(hasher)
			}
		}
	}
	return nil
}

func (r *measuredFiles) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	var val2 int
	err = gobtools.DecodeInt(buf, &val2)
	if err != nil {
		return err
	}
	if val2 != -1 {
		r.paths = make([]android.WritablePath, val2)
		for val3 := 0; val3 < int(val2); val3++ {
			if val5, err := gobtools.DecodeInterface(ctx, buf); err != nil {
				return err
			} else if val5 == nil {
				r.paths[val3] = nil
			} else {
				r.paths[val3] = val5.(android.WritablePath)
			}
		}
	}

	return err
}

var measuredFilesGobRegId int16

func (r measuredFiles) GetTypeId() int16 {
	return measuredFilesGobRegId
}

// end of bloaty.go
