// Code generated by go run gob_gen.go; DO NOT EDIT.

package provenance

import (
	"android/soong/android"
	"bytes"
	"fmt"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
	"reflect"
)

// begin of provenance_singleton.go
func init() {
	ProvenanceMetadataInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ProvenanceMetadataInfo) })
}

func (r ProvenanceMetadataInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(ctx, buf, r.ProvenanceMetaDataFile); err != nil {
		return err
	}
	return err
}

func (r ProvenanceMetadataInfo) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":provenance.ProvenanceMetadataInfo")
	hasher.WriteInt(1)
	hasher.WriteString(":provenance.android.Path")
	val1 := r.ProvenanceMetaDataFile == nil
	if val1 {
		hasher.WriteByte(0)
	} else {
		if v := reflect.ValueOf(r.ProvenanceMetaDataFile); v.Kind() == reflect.Ptr {
			if v.IsNil() {
				panic(fmt.Errorf("nil pointer is not supported in interface"))
			} else {
				val2 := r.ProvenanceMetaDataFile == nil
				if val2 {
					hasher.WriteByte(0)
				} else {
					val3 := func(hasher *proptools.Hasher) error {
						return r.ProvenanceMetaDataFile.(proptools.CustomHash).CustomHash(hasher)
					}
					if err := proptools.HashReference(hasher, uintptr(v.Pointer()), val3); err != nil {
						return err
					}
				}
			}
		} else {
			r.ProvenanceMetaDataFile.(proptools.CustomHash).CustomHash(hasher)
		}
	}
	return nil
}

func (r *ProvenanceMetadataInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(ctx, buf); err != nil {
		return err
	} else if val2 == nil {
		r.ProvenanceMetaDataFile = nil
	} else {
		r.ProvenanceMetaDataFile = val2.(android.Path)
	}

	return err
}

var ProvenanceMetadataInfoGobRegId int16

func (r ProvenanceMetadataInfo) GetTypeId() int16 {
	return ProvenanceMetadataInfoGobRegId
}

// end of provenance_singleton.go
