# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scripts/ninjago_analyzer/ninjago_log.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*scripts/ninjago_analyzer/ninjago_log.proto\x12\x10ninjago_analyzer\"]\n\x0bNinjaTarget\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0crequest_hash\x18\x02 \x01(\t\x12\x15\n\rresponse_hash\x18\x03 \x01(\t\x12\x13\n\x0bhidden_deps\x18\x04 \x03(\t\":\n\x08NinjaLog\x12.\n\x07targets\x18\x01 \x03(\x0b\x32\x1d.ninjago_analyzer.NinjaTargetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scripts.ninjago_analyzer.ninjago_log_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NINJATARGET._serialized_start=64
  _NINJATARGET._serialized_end=157
  _NINJALOG._serialized_start=159
  _NINJALOG._serialized_end=217
# @@protoc_insertion_point(module_scope)
