// Code generated by go run gob_gen.go; DO NOT EDIT.

package cipd

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/proptools"
)

// begin of cipd_package.go
func init() {
	CipdPackageInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(CipdPackageInfo) })
}

func (r CipdPackageInfo) Encode(ctx gobtools.EncContext, buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.FullPackageName); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.Version); err != nil {
		return err
	}
	return err
}

func (r CipdPackageInfo) CustomHash(hasher *proptools.Hasher) error {
	hasher.WriteString(":cipd.CipdPackageInfo")
	hasher.WriteInt(2)
	hasher.WriteString(":.string")
	hasher.WriteString(r.FullPackageName)
	hasher.WriteString(":.string")
	hasher.WriteString(r.Version)
	return nil
}

func (r *CipdPackageInfo) Decode(ctx gobtools.EncContext, buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.FullPackageName)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.Version)
	if err != nil {
		return err
	}

	return err
}

var CipdPackageInfoGobRegId int16

func (r CipdPackageInfo) GetTypeId() int16 {
	return CipdPackageInfoGobRegId
}

// end of cipd_package.go
