#!/usr/bin/env bash
#
# Copyright 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -euo pipefail

build/soong/soong_ui.bash --make-mode dist test-configs-zip reduce-test-configs || exit $?

host_out=$(build/soong/soong_ui.bash --dumpvar-mode HOST_OUT)
top=$(build/soong/soong_ui.bash --dumpvar-mode --abs TOP)

set -f # Disable glob expansion to allow pass through.
$host_out/bin/reduce-test-configs -top $top $@ || exit $?
set +f # Re-enable.
